name = "software-hub"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "software-hub"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"


